# Generated by Django 2.2.19 on 2022-09-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshrt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
